[package]
name = "efi"
version = "0.1.0"
authors = ["Gurinder Singh <frederick.the.fool@gmail.com>"]

[dependencies]
bitflags = "1.0"

[dependencies.failure]
version = "0.1.1"
default-features = false
features = ["derive"]
